// SPDX-License-Identifier: Apache-2.0
// @generated by scripts/generate-bindings.py from docs/derived-core-schema.json -- DO NOT EDIT.
// Machine-generated safe `Db` read accessors. include!()'d into lib.rs (unix only),
// so this file uses line comments (an inner //! doc is illegal mid-file).

impl Db {
    pub fn block_get_name(&self) -> String { sys::block_get_name(self.r()) }
    pub fn block_get_const_name(&self) -> String { sys::block_get_const_name(self.r()) }
    pub fn block_get_tech(&self) -> String { sys::block_get_tech(self.r()) }
    pub fn block_get_parent(&self) -> String { sys::block_get_parent(self.r()) }
    pub fn block_get_parent_inst(&self) -> String { sys::block_get_parent_inst(self.r()) }
    pub fn block_get_children(&self) -> Vec<String> { (0..sys::num_block_get_children(self.r())).map(|i| sys::nth_block_get_children(self.r(), i)).collect() }
    pub fn block_get_b_terms(&self) -> Vec<String> { (0..sys::num_block_get_b_terms(self.r())).map(|i| sys::nth_block_get_b_terms(self.r(), i)).collect() }
    pub fn block_get_i_terms(&self) -> Vec<String> { (0..sys::num_block_get_i_terms(self.r())).map(|i| sys::nth_block_get_i_terms(self.r(), i)).collect() }
    pub fn block_get_insts(&self) -> Vec<String> { (0..sys::num_block_get_insts(self.r())).map(|i| sys::nth_block_get_insts(self.r(), i)).collect() }
    pub fn block_get_mod_nets(&self) -> Vec<String> { (0..sys::num_block_get_mod_nets(self.r())).map(|i| sys::nth_block_get_mod_nets(self.r(), i)).collect() }
    pub fn block_get_nets(&self) -> Vec<String> { (0..sys::num_block_get_nets(self.r())).map(|i| sys::nth_block_get_nets(self.r(), i)).collect() }
    pub fn block_get_vias(&self) -> Vec<String> { (0..sys::num_block_get_vias(self.r())).map(|i| sys::nth_block_get_vias(self.r(), i)).collect() }
    pub fn block_get_def_units(&self) -> i32 { sys::block_get_def_units(self.r()) }
    pub fn block_get_db_units_per_micron(&self) -> i32 { sys::block_get_db_units_per_micron(self.r()) }
    pub fn block_get_corner_count(&self) -> i32 { sys::block_get_corner_count(self.r()) }
    pub fn block_get_corners_per_block(&self) -> i32 { sys::block_get_corners_per_block(self.r()) }
    pub fn block_get_ext_db_count(&self) -> i32 { sys::block_get_ext_db_count(self.r()) }
    pub fn block_get_corner_name_list(&self) -> String { sys::block_get_corner_name_list(self.r()) }
    pub fn block_get_rows(&self) -> Vec<String> { (0..sys::num_block_get_rows(self.r())).map(|i| sys::nth_block_get_rows(self.r(), i)).collect() }
    pub fn block_get_min_routing_layer(&self) -> i32 { sys::block_get_min_routing_layer(self.r()) }
    pub fn block_get_max_routing_layer(&self) -> i32 { sys::block_get_max_routing_layer(self.r()) }
    pub fn block_get_min_layer_for_clock(&self) -> i32 { sys::block_get_min_layer_for_clock(self.r()) }
    pub fn block_get_max_layer_for_clock(&self) -> i32 { sys::block_get_max_layer_for_clock(self.r()) }
    pub fn block_get_g_cell_tile_size(&self) -> i32 { sys::block_get_g_cell_tile_size(self.r()) }
    pub fn block_get_regions(&self) -> Vec<String> { (0..sys::num_block_get_regions(self.r())).map(|i| sys::nth_block_get_regions(self.r(), i)).collect() }
    pub fn block_get_non_default_rules(&self) -> Vec<String> { (0..sys::num_block_get_non_default_rules(self.r())).map(|i| sys::nth_block_get_non_default_rules(self.r(), i)).collect() }
    pub fn inst_get_name(&self, inst: &str) -> String { sys::inst_get_name(self.r(), inst) }
    pub fn inst_get_const_name(&self, inst: &str) -> String { sys::inst_get_const_name(self.r(), inst) }
    pub fn inst_get_orient(&self, inst: &str) -> String { sys::inst_get_orient(self.r(), inst) }
    pub fn inst_get_placement_status(&self, inst: &str) -> String { sys::inst_get_placement_status(self.r(), inst) }
    pub fn inst_is_fixed(&self, inst: &str) -> bool { sys::inst_is_fixed(self.r(), inst) }
    pub fn inst_is_placed(&self, inst: &str) -> bool { sys::inst_is_placed(self.r(), inst) }
    pub fn inst_get_eco_create(&self, inst: &str) -> bool { sys::inst_get_eco_create(self.r(), inst) }
    pub fn inst_get_eco_destroy(&self, inst: &str) -> bool { sys::inst_get_eco_destroy(self.r(), inst) }
    pub fn inst_get_eco_modify(&self, inst: &str) -> bool { sys::inst_get_eco_modify(self.r(), inst) }
    pub fn inst_get_user_flag1(&self, inst: &str) -> bool { sys::inst_get_user_flag1(self.r(), inst) }
    pub fn inst_get_user_flag2(&self, inst: &str) -> bool { sys::inst_get_user_flag2(self.r(), inst) }
    pub fn inst_get_user_flag3(&self, inst: &str) -> bool { sys::inst_get_user_flag3(self.r(), inst) }
    pub fn inst_is_do_not_touch(&self, inst: &str) -> bool { sys::inst_is_do_not_touch(self.r(), inst) }
    pub fn inst_get_block(&self, inst: &str) -> String { sys::inst_get_block(self.r(), inst) }
    pub fn inst_get_master(&self, inst: &str) -> String { sys::inst_get_master(self.r(), inst) }
    pub fn inst_get_i_terms(&self, inst: &str) -> Vec<String> { (0..sys::num_inst_get_i_terms(self.r(), inst)).map(|i| sys::nth_inst_get_i_terms(self.r(), inst, i)).collect() }
    pub fn inst_get_first_input(&self, inst: &str) -> String { sys::inst_get_first_input(self.r(), inst) }
    pub fn inst_get_first_output(&self, inst: &str) -> String { sys::inst_get_first_output(self.r(), inst) }
    pub fn inst_get_region(&self, inst: &str) -> String { sys::inst_get_region(self.r(), inst) }
    pub fn inst_get_child(&self, inst: &str) -> String { sys::inst_get_child(self.r(), inst) }
    pub fn inst_get_parent(&self, inst: &str) -> String { sys::inst_get_parent(self.r(), inst) }
    pub fn inst_get_children(&self, inst: &str) -> Vec<String> { (0..sys::num_inst_get_children(self.r(), inst)).map(|i| sys::nth_inst_get_children(self.r(), inst, i)).collect() }
    pub fn inst_is_hierarchical(&self, inst: &str) -> bool { sys::inst_is_hierarchical(self.r(), inst) }
    pub fn inst_is_physical_only(&self, inst: &str) -> bool { sys::inst_is_physical_only(self.r(), inst) }
    pub fn inst_get_weight(&self, inst: &str) -> i32 { sys::inst_get_weight(self.r(), inst) }
    pub fn inst_get_source_type(&self, inst: &str) -> String { sys::inst_get_source_type(self.r(), inst) }
    pub fn inst_is_block(&self, inst: &str) -> bool { sys::inst_is_block(self.r(), inst) }
    pub fn inst_is_core(&self, inst: &str) -> bool { sys::inst_is_core(self.r(), inst) }
    pub fn inst_is_pad(&self, inst: &str) -> bool { sys::inst_is_pad(self.r(), inst) }
    pub fn inst_is_end_cap(&self, inst: &str) -> bool { sys::inst_is_end_cap(self.r(), inst) }
    pub fn inst_get_pin_access_idx(&self, inst: &str) -> u32 { sys::inst_get_pin_access_idx(self.r(), inst) }
    pub fn net_get_name(&self, net: &str) -> String { sys::net_get_name(self.r(), net) }
    pub fn net_get_const_name(&self, net: &str) -> String { sys::net_get_const_name(self.r(), net) }
    pub fn net_is_r_c_disconnected(&self, net: &str) -> bool { sys::net_is_r_c_disconnected(self.r(), net) }
    pub fn net_get_weight(&self, net: &str) -> i32 { sys::net_get_weight(self.r(), net) }
    pub fn net_get_source_type(&self, net: &str) -> String { sys::net_get_source_type(self.r(), net) }
    pub fn net_get_x_talk_class(&self, net: &str) -> i32 { sys::net_get_x_talk_class(self.r(), net) }
    pub fn net_get_driving_i_term(&self, net: &str) -> String { sys::net_get_driving_i_term(self.r(), net) }
    pub fn net_has_fixed_bump(&self, net: &str) -> bool { sys::net_has_fixed_bump(self.r(), net) }
    pub fn net_get_wire_type(&self, net: &str) -> String { sys::net_get_wire_type(self.r(), net) }
    pub fn net_get_sig_type(&self, net: &str) -> String { sys::net_get_sig_type(self.r(), net) }
    pub fn net_is_marked(&self, net: &str) -> bool { sys::net_is_marked(self.r(), net) }
    pub fn net_is_mark_1ed(&self, net: &str) -> bool { sys::net_is_mark_1ed(self.r(), net) }
    pub fn net_is_select(&self, net: &str) -> bool { sys::net_is_select(self.r(), net) }
    pub fn net_is_wire_ordered(&self, net: &str) -> bool { sys::net_is_wire_ordered(self.r(), net) }
    pub fn net_is_disconnected(&self, net: &str) -> bool { sys::net_is_disconnected(self.r(), net) }
    pub fn net_is_wire_altered(&self, net: &str) -> bool { sys::net_is_wire_altered(self.r(), net) }
    pub fn net_is_r_cgraph(&self, net: &str) -> bool { sys::net_is_r_cgraph(self.r(), net) }
    pub fn net_is_extracted(&self, net: &str) -> bool { sys::net_is_extracted(self.r(), net) }
    pub fn net_is_spef(&self, net: &str) -> bool { sys::net_is_spef(self.r(), net) }
    pub fn net_is_do_not_touch(&self, net: &str) -> bool { sys::net_is_do_not_touch(self.r(), net) }
    pub fn net_get_block(&self, net: &str) -> String { sys::net_get_block(self.r(), net) }
    pub fn net_get_i_terms(&self, net: &str) -> Vec<String> { (0..sys::num_net_get_i_terms(self.r(), net)).map(|i| sys::nth_net_get_i_terms(self.r(), net, i)).collect() }
    pub fn net_get1st_i_term(&self, net: &str) -> String { sys::net_get1st_i_term(self.r(), net) }
    pub fn net_get_first_driver_inst(&self, net: &str) -> String { sys::net_get_first_driver_inst(self.r(), net) }
    pub fn net_get_first_output(&self, net: &str) -> String { sys::net_get_first_output(self.r(), net) }
    pub fn net_get_b_terms(&self, net: &str) -> Vec<String> { (0..sys::num_net_get_b_terms(self.r(), net)).map(|i| sys::nth_net_get_b_terms(self.r(), net, i)).collect() }
    pub fn net_get1st_b_term(&self, net: &str) -> String { sys::net_get1st_b_term(self.r(), net) }
    pub fn net_is_connected_by_abutment(&self, net: &str) -> bool { sys::net_is_connected_by_abutment(self.r(), net) }
    pub fn net_is_i_o(&self, net: &str) -> bool { sys::net_is_i_o(self.r(), net) }
    pub fn net_is_wild_connected(&self, net: &str) -> bool { sys::net_is_wild_connected(self.r(), net) }
    pub fn net_get_gndc_calib_factor(&self, net: &str) -> f32 { sys::net_get_gndc_calib_factor(self.r(), net) }
    pub fn net_get_cc_calib_factor(&self, net: &str) -> f32 { sys::net_get_cc_calib_factor(self.r(), net) }
    pub fn net_get_cc_adjust_factor(&self, net: &str) -> f32 { sys::net_get_cc_adjust_factor(self.r(), net) }
    pub fn net_get_cc_adjust_order(&self, net: &str) -> u32 { sys::net_get_cc_adjust_order(self.r(), net) }
    pub fn net_get_db_cc(&self, net: &str) -> f32 { sys::net_get_db_cc(self.r(), net) }
    pub fn net_get_ref_cc(&self, net: &str) -> f32 { sys::net_get_ref_cc(self.r(), net) }
    pub fn net_get_cc_match_ratio(&self, net: &str) -> f32 { sys::net_get_cc_match_ratio(self.r(), net) }
    pub fn net_get1st_r_seg_id(&self, net: &str) -> u32 { sys::net_get1st_r_seg_id(self.r(), net) }
    pub fn net_get1st_cap_node_id(&self, net: &str) -> u32 { sys::net_get1st_cap_node_id(self.r(), net) }
    pub fn net_get_r_seg_count(&self, net: &str) -> u32 { sys::net_get_r_seg_count(self.r(), net) }
    pub fn net_max_internal_cap_num(&self, net: &str) -> u32 { sys::net_max_internal_cap_num(self.r(), net) }
    pub fn net_get_cap_node_count(&self, net: &str) -> u32 { sys::net_get_cap_node_count(self.r(), net) }
    pub fn net_get_cc_count(&self, net: &str) -> u32 { sys::net_get_cc_count(self.r(), net) }
    pub fn net_get_non_default_rule(&self, net: &str) -> String { sys::net_get_non_default_rule(self.r(), net) }
    pub fn net_get_term_count(&self, net: &str) -> u32 { sys::net_get_term_count(self.r(), net) }
    pub fn net_get_i_term_count(&self, net: &str) -> u32 { sys::net_get_i_term_count(self.r(), net) }
    pub fn net_get_b_term_count(&self, net: &str) -> u32 { sys::net_get_b_term_count(self.r(), net) }
    pub fn net_has_jumpers(&self, net: &str) -> bool { sys::net_has_jumpers(self.r(), net) }
    pub fn net_find_mod_net_in_highest_hier(&self, net: &str) -> String { sys::net_find_mod_net_in_highest_hier(self.r(), net) }
    pub fn bterm_get_name(&self, bterm: &str) -> String { sys::bterm_get_name(self.r(), bterm) }
    pub fn bterm_get_const_name(&self, bterm: &str) -> String { sys::bterm_get_const_name(self.r(), bterm) }
    pub fn bterm_get_sig_type(&self, bterm: &str) -> String { sys::bterm_get_sig_type(self.r(), bterm) }
    pub fn bterm_get_io_type(&self, bterm: &str) -> String { sys::bterm_get_io_type(self.r(), bterm) }
    pub fn bterm_is_set_spef_mark(&self, bterm: &str) -> bool { sys::bterm_is_set_spef_mark(self.r(), bterm) }
    pub fn bterm_is_set_mark(&self, bterm: &str) -> bool { sys::bterm_is_set_mark(self.r(), bterm) }
    pub fn bterm_get_ext_id(&self, bterm: &str) -> u32 { sys::bterm_get_ext_id(self.r(), bterm) }
    pub fn bterm_is_special(&self, bterm: &str) -> bool { sys::bterm_is_special(self.r(), bterm) }
    pub fn bterm_get_net(&self, bterm: &str) -> String { sys::bterm_get_net(self.r(), bterm) }
    pub fn bterm_get_mod_net(&self, bterm: &str) -> String { sys::bterm_get_mod_net(self.r(), bterm) }
    pub fn bterm_get_block(&self, bterm: &str) -> String { sys::bterm_get_block(self.r(), bterm) }
    pub fn bterm_get_i_term(&self, bterm: &str) -> String { sys::bterm_get_i_term(self.r(), bterm) }
    pub fn bterm_get_first_pin_placement_status(&self, bterm: &str) -> String { sys::bterm_get_first_pin_placement_status(self.r(), bterm) }
    pub fn bterm_get_ground_pin(&self, bterm: &str) -> String { sys::bterm_get_ground_pin(self.r(), bterm) }
    pub fn bterm_get_supply_pin(&self, bterm: &str) -> String { sys::bterm_get_supply_pin(self.r(), bterm) }
    pub fn bterm_sta_vertex_id(&self, bterm: &str) -> u32 { sys::bterm_sta_vertex_id(self.r(), bterm) }
    pub fn bterm_get_mirrored_b_term(&self, bterm: &str) -> String { sys::bterm_get_mirrored_b_term(self.r(), bterm) }
    pub fn bterm_has_mirrored_b_term(&self, bterm: &str) -> bool { sys::bterm_has_mirrored_b_term(self.r(), bterm) }
    pub fn bterm_is_mirrored(&self, bterm: &str) -> bool { sys::bterm_is_mirrored(self.r(), bterm) }
}
